### get one song
GET http://localhost:3000/songs/1

### Get all songs
GET http://localhost:3000/songs/?page=1&limit=5

### update song
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "title": "New Track Very Popular",
  "releasedDate": "2024-08-06",
  "artists": [1, 2, 3],
  "duration": "02:54",
  "lyrics": "These are the lyrics of the song."
}

### delete song
DELETE http://localhost:3000/songs/1

### create song
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1ekBleGFtcGxlLmNvbSIsInVzZXJJZCI6MTUsImFydGlzdElkIjo1LCJpYXQiOjE3Mjk2MDYwMTAsImV4cCI6MTcyOTY5MjQxMH0.J5b_gURMPdtYQMTvBgIB5m5KCNyaBQcsCfLQfEQeFqg

{
  "title": "New Song Title9",
  "artists": [5],
  "releasedDate": "2024-08-06",
  "duration": "02:54",
  "lyrics": "These are the lyrics of the song."
}
