### create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john_doe@example.com",
  "password": "securepassword123",
  "twoFASecret": "your-2fa-secret",
  "enable2FA": false,
  "apiKey": "your-api-key"
}

